pool:
  vmImage: ubuntu-latest

variables:
  - template: variables/main.yml

stages:
- stage: ZipArtifact
  displayName: Zip Artifact

  jobs:
    - job: Build

      steps:
        - checkout: self
          submodules: recursive

        - task: ArchiveFiles@2
          displayName: 'Archive Protos'

          inputs:
            rootFolderOrFile: '.'
            includeRootFolder: false
            archiveType: 'tar'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            replaceExistingArchive: true

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact'

          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(APP_FOLDER_NAME).tar.gz'
            ArtifactName: '$(APP_FOLDER_NAME)-artifact'
            publishLocation: 'Container'
